// Neuigkeiten / What's new — nur für Nutzer sichtbare Änderungen, neueste zuerst.
// Neuer Eintrag: oben ein { date: "JJJJ-MM-TT", items: [{ de: "…", en: "…" }] } ergänzen
// (oder an ein bestehendes Datum anhängen). Keine internen Details (Zugang, Build, Technik).
// Reines Datenmodul ohne DOM-Import, damit der Test es direkt mit node laden kann.

export const CHANGELOG = [
  {
    date: "2026-10-07",
    items: [
      { de: "Meine Grooves: „Speichern als…“ legt jetzt immer einen neuen Groove an und überschreibt keinen anderen mehr. Nach dem Speichern beginnt „Erstellen“ mit einem leeren Groove.",
        en: "My grooves: Save as… now always creates a new groove and never overwrites another one. After saving, a new groove starts empty." },
      { de: "Meine Grooves: Einen gespeicherten Groove unter Üben mit „Bearbeiten“ ändern und mit „Speichern“ aktualisieren – oder mit „Speichern als…“ als Kopie behalten.",
        en: "My grooves: open a saved groove under Practice, tap Edit to change it and Save to update it – or Save as… to keep a copy." },
      { de: "Meine Grooves quer: Die Taktwahl 1–4 sitzt oben neben den Ansichten und liegt beim Scrollen nicht mehr über den Feldern.",
        en: "My grooves in landscape: the 1–4 bar selector sits in the top row next to the tabs and no longer covers the pads when you scroll." },
      { de: "Meine Grooves: Alle Knöpfe und der Hinweis zum Querdrehen gibt es jetzt auch auf Englisch.",
        en: "My grooves: every button and the hint to turn your phone sideways now appear in English too." },
      { de: "Lexikon: Bildbeschreibungen für 13 Begriffs-Bilder ergänzt – hilfreich mit Screenreader.",
        en: "Glossary: image descriptions added for 13 term pictures – helpful with a screen reader." },
      { de: "Meine Grooves: 1. und 4. 16tel stehen jetzt richtig als punktierte Achtel plus 16tel, leere Schläge und Takte zeigen Pausen. Die Zählzeile zeigt wie die Hilfen „1 e + a“, in Takt 1 steht kein „Takt 0“ mehr, „Löschen“ fragt vorher nach, und quer liegt das Start-Rad beim Üben neben den Noten. Die Bassdrum steht jetzt im untersten Zwischenraum.",
        en: "My grooves: the 1st and 4th 16th are now written correctly as a dotted eighth plus a 16th, and empty beats and bars show rests. The count row reads “1 e + a” like the helpers, bar 1 no longer shows “Bar 0”, Delete asks first, and in landscape the Start dial sits next to the notes when you practise. The bass drum now sits in the bottom space of the staff." },
    ],
  },
  {
    date: "2026-10-06",
    items: [
      { de: "Meine Grooves ist da: Hi-Hat, Snare und Bass bauen, quer eintippen, hochkant den Rhythmus sehen, mit der Dial üben und unter einem Namen auf diesem Gerät behalten.",
        en: "My grooves is here: create a groove with hi-hat, snare and bass, enter it in landscape, see the rhythm in portrait, practise with the dial and keep it under a name on this device." },
      { de: "Eingabe: Zählzeiten über jedem Feld, Hilfen 1, + und e a für die aktive Zeile, Taktzahl 1–4 im Querformat, Speichern als… fragt den Namen ab. Die Vorschau sitzt oben rechts.",
        en: "Input: counts above each pad, 1, + and e a helpers for the active row, 1–4 bars in landscape, Save as… asks for the name. The preview sits at the top right." },
      { de: "Üben: Nur Click, Playback oder Beides. Der Click blinkt nur auf den vollen Zählzeiten. Alle Stimmen hängen an einem Balken, die Bassdrum bleibt unten.",
        en: "Practice: click only, playback or both. The click flashes only on the beat. All voices share one beam, the bass drum stays low." },
      { de: "Meine Grooves: Alle Notenhälse zeigen nach oben, auch bei der Bassdrum. Erste und letzte 16tel einer Vierergruppe stehen als punktierte Achtel plus 16tel, wie bei Rudiment 33.",
        en: "My grooves: all stems point up, the bass drum included. The first and last 16th of a beat are written as a dotted eighth plus a 16th, like rudiment 33." },
      { de: "Zum Eintippen in Meine Grooves das Handy quer drehen – die Felder werden größer.",
        en: "Turn the phone sideways to enter a rhythm in My grooves – the pads get bigger." },
      { de: "Multiple Bounce Roll klingt im Vorspiel jetzt als Presswirbel, nicht mehr als einzelner Schlag.",
        en: "The multiple bounce roll now plays back as a press roll, not a single stroke." },
      { de: "Rudiments: R ist grau, L ist türkis. Der laufende Schlag leuchtet türkis.",
        en: "Rudiments: R is grey, L is teal. The current stroke lights up teal." },
    ],
  },
  {
    date: "2026-10-05",
    items: [
      { de: "Hand Control: Die aktuelle Übung steht jetzt auf einer hellen Karte – besser lesbar.",
        en: "Hand Control: the current exercise now sits on a light card for easier reading." },
      { de: "Hand Control, Fokus-Mode: In der letzten Wiederholung wechselt die aktuelle Übung Gruppe für Gruppe in die nächste – weich ausgeblendet, ohne harten Schnitt.",
        en: "Hand Control, Focus mode: on the last repeat, the current exercise fades group by group into the next – soft swap, no hard cut." },
      { de: "Rhythmuspyramide: Beim Üben stehen „Jetzt“ und „Als Nächstes“ als zwei helle Karten nebeneinander, jeweils mit Notenfigur und Name der Stufe.",
        en: "Rhythm Pyramid: while you play, “Now” and “Next up” sit side by side on two light cards, each with the note figure and the name of the stage." },
    ],
  },
  {
    date: "2026-10-04",
    items: [
      { de: "Neuigkeiten öffnest du jetzt mit dem „!“ unter dem „?“ – ein türkiser Punkt zeigt, wenn es etwas Neues gibt.",
        en: "What’s new now opens with the “!” under the “?” – a teal dot shows when there is something new." },
      { de: "Lexikon: 17 neue Begriffs-Bilder – Akzent, Backbeat, Four on the Floor, Offbeat, Ghost Note, Flam, Wirbel, Paradiddle, Triole, Cross Stick, Cowbell, Kessel, Fell, Spannreifen, Sticks und Besen, Mallets und Taktarten. Neue Einträge: Fell, Spannreifen, Sticks und Besen, Taktarten.",
        en: "Glossary: 17 new term pictures – accent, backbeat, four on the floor, offbeat, ghost note, flam, roll, paradiddle, triplet, cross stick, cowbell, shell, drumhead, hoop, sticks and brushes, mallets and time signatures. New entries: drumhead, hoop, sticks and brushes, time signatures." },
      { de: "Lexikon: 40 Einträge haben jetzt Bilder – Notenwerte, Pausen, Teile des Drumsets und Begriffsschilder. Antippen zeigt das Bild groß. Neu sind 8 Einträge: Ganze Note, Zweiunddreißigstel, Das Drumset, Hängetom, Standtom, Splash, Hardware und Hi-Hat-Maschine.",
        en: "Glossary: 40 entries now have pictures – note values, rests, parts of the drum kit and term cards. Tap a picture to see it full size. 8 new entries: whole note, thirty-second note, the drum kit, rack tom, floor tom, splash, hardware and hi-hat stand." },
      { de: "Datenschutz: Erklärung aktualisiert (keine Google-Schriften mehr) und jetzt auch öffentlich im Web lesbar.",
        en: "Privacy: policy updated (no more Google fonts) and now also publicly readable on the web." },
      { de: "Schriften sind jetzt in der App eingebaut – schneller, offline nutzbar und ohne Verbindung zu Google.",
        en: "Fonts are now built into the app – faster, works offline and no connection to Google." },
      { de: "Rudiments: Hörmodus „Tom / Snare“ – rechts Floortom, links Snare (statt L / R).",
        en: "Rudiments: new sound mode “Tom / Snare” – right hand floor tom, left hand snare (replaces L / R)." },
      { de: "Lexikon: Der Eintrag „Schlagfertig‽“ sieht jetzt aus wie im Logo – türkis und mit ‽. Neu erklärt: das ‽ ist Frage- und Ausrufezeichen zugleich.",
        en: "Glossary: the “Schlagfertig‽” entry now looks like the logo – teal and with ‽. New: it explains that ‽ is a question mark and exclamation mark in one." },
    ],
  },
  {
    date: "2026-10-03",
    items: [
      { de: "Startseite: Die Kacheln sind jetzt deutlich durchsichtiger – das Logo scheint durch.",
        en: "Home screen: the tiles are now much more see-through – the logo shows through." },
      { de: "Lexikon: Begriffe und Rudiment-Infos gibt es jetzt auch auf Englisch. Neu ist der Eintrag „Schlagfertig“, und ein Tipp auf einen Buchstaben springt jetzt zum Buchstaben statt zur Startseite.",
        en: "Glossary: terms and rudiment info are now available in English too. New: an entry for “Schlagfertig”, and tapping a letter now jumps to that letter instead of the home screen." },
      { de: "Startseite: „Nicht heute“ sitzt jetzt unten rechts auf der Karte und wird beim Scrollen nicht mehr verdeckt.",
        en: "Home screen: “Not today” now sits at the bottom right of the card and is no longer covered when you scroll." },
      { de: "Startseite: Das Logo bleibt beim Scrollen stehen, die Karten gleiten wie Glas darüber.",
        en: "Home screen: the logo stays in place while you scroll, and the cards glide over it like glass." },
      { de: "Karte „Heute“: Plan A mit 5 Minuten Pyramide, Plan C „Kurz“ jetzt ohne Noten, dafür 6 Minuten Single Stroke Roll.",
        en: "“Today” card: plan A now has 5 minutes of pyramid; plan C “Short” drops the sheet music and has 6 minutes of single stroke roll instead." },
    ],
  },
  {
    date: "2026-10-02",
    items: [
      { de: "Neu: Lexikon – kurze Erklärungen zu Begriffen wie Downbeat, Flam oder Groove, von A bis Z durchsuchbar. Bei den Rudiments zeigt „Info“ jetzt mehr zum jeweiligen Rudiment.",
        en: "New: Glossary – short explanations of terms like downbeat, flam or groove, searchable from A to Z. In Rudiments, “Info” now tells you more about each rudiment." },
      { de: "Hand Control: Die Triolen-Ansicht („ternär“) ist vorerst wieder ausgeblendet, und Start funktioniert wieder wie gewohnt.",
        en: "Hand Control: the triplet view (“Triplets”) is hidden again for now, and Start works as usual again." },
      { de: "Startseite: Auf der Karte „Erste Übung starten“ gibt es jetzt „Nicht heute“ – die Karte ist dann bis morgen ausgeblendet, und die Karte „Heute“ rückt nach oben.",
        en: "Home screen: the “Start your first lesson” card now has “Not today” – the card is hidden until tomorrow and the “Today” card moves up." },
      { de: "Startseite: neue Karte „Heute“ mit drei kurzen Übeplänen (A, B, C). Jeder Schritt öffnet das passende Modul mit ruhigem Starttempo – zurück geht es zur selben Stelle der Startseite.",
        en: "Home screen: new “Today” card with three short practice plans (A, B, C). Each step opens the matching module at a calm starting tempo – Back returns you to the same spot on the home screen." },
      { de: "Hand Control: eigene Übungen – alle 24 Nummern sind neu.",
        en: "Hand Control: own exercises – all 24 patterns are new." },
    ],
  },
  {
    date: "2026-10-01",
    items: [
      { de: "Startseite: Unten gibt es jetzt drei Knöpfe für WhatsApp, Instagram und E-Mail – so erreichst du mich direkt.",
        en: "Home screen: three buttons at the bottom for WhatsApp, Instagram and email – get in touch with me directly." },
      { de: "Hilfe auf der Startseite (?): Die Zeile zu Rudiments nutzt jetzt denselben Text wie die Kachel; bei Noten steht jetzt, dass du im Vollbild zoomen kannst.",
        en: "Home screen help (?): the Rudiments line now uses the same text as the tile; the Sheet Music line now mentions that you can zoom in full screen." },
      { de: "Startseite: neue Texte auf den Kacheln Erste Übung, Click-Trainer, Rhythmuspyramide und Noten; Zeilen brechen ausgeglichen um.",
        en: "Home screen: new texts on the First Lesson, Click Trainer, Rhythm Pyramid and Sheet Music tiles; lines wrap evenly." },
      { de: "Verstecktes Metronom (Logo auf der Startseite antippen): Jetzt mit demselben Clickwheel wie der Click-Trainer – am Ring drehen, der Daumen folgt dem Finger.",
        en: "Hidden metronome (tap the logo on the home screen): now has the same clickwheel as the Click Trainer – turn the ring and the thumb follows your finger." },
      { de: "Startseite: neuer Text auf der Rudiments-Kachel – „40 Grundlagen für Technik, Kontrolle und Timing. Mit Notation, Click und Tempo.“",
        en: "Home screen: new text on the Rudiments tile – “40 essentials for technique, control and timing. With notation, click and tempo.”" },
      { de: "Jede Seite öffnet jetzt oben – auch wenn du auf der Startseite weit nach unten gescrollt hast, ist der Zurück-Knopf sofort da. Zurück auf der Startseite landest du wieder dort, wo du warst.",
        en: "Every page now opens at the top – even if you scrolled far down on the home screen, the Back button is right there. Going back to the home screen returns you to where you were." },
      { de: "Flagge und Fragezeichen liegen nicht mehr unter der iPhone-Statusleiste, wenn die App vom Home-Bildschirm gestartet wird. App-Icon wird wieder geladen.",
        en: "Flag and help button no longer hide under the iPhone status bar when launched from the home screen. App icon loads again." },
    ],
  },
  {
    date: "2026-09-30",
    items: [
      { de: "Noten: Große PDFs (z. B. Poster) zeigt das Vollbild jetzt ganz – eingepasst, nichts abgeschnitten. Mit zwei Fingern oder Doppeltipp zoomst du bis 5× hinein (bleibt scharf), gezoomt verschiebst du mit einem Finger. Unten − / + und „Ganz“ zum Zurücksetzen; mehrseitige PDFs blätterst du mit ▲ ▼. Wischen zum nächsten Blatt klappt nur ungezoomt.",
        en: "Sheet Music: full screen now shows large PDFs (e.g. posters) completely – fitted, nothing cut off. Pinch or double-tap to zoom in up to 5× (stays sharp); when zoomed, drag with one finger. Use − / + and “Fit” at the bottom to reset; flip through multi-page PDFs with ▲ ▼. Swiping to the next sheet only works when not zoomed." },
      { de: "Rudiments: #2 Single Stroke Four jetzt als 2/4-Takt – pro Schlag eine 16tel-Triole mit betonter Achtel.",
        en: "Rudiments: #2 Single Stroke Four is now a 2/4 bar – each beat is a sixteenth-note triplet plus an accented eighth note." },
      { de: "Tempo-Rad: Rudiments, Rhythmuspyramide und Hand Control haben jetzt dasselbe Clickwheel wie der Click-Trainer – antippen, am Ring drehen, der Daumen folgt dem Finger. Hand Control: Der Wiederholungs-Zähler bleibt beim Drehen frei sichtbar.",
        en: "Tempo wheel: Rudiments, Rhythm Pyramid and Hand Control now have the same click wheel as the Click Trainer – tap, turn the ring, the thumb follows your finger. Hand Control: the repeat counter stays clearly visible while you turn." },
      { de: "Seiten federn nicht mehr nach; Hand Control: Liste steht still, solange der Click läuft.",
        en: "Pages no longer bounce; Hand Control: the list stays put while the click is running." },
      { de: "Startseite: Copyright größer, Links kleiner. Clickwheel: Hebel folgt dem Finger.",
        en: "Home screen: copyright larger, links smaller. Click wheel: the lever follows your finger." },
      { de: "Noten: Blatt antippen öffnet eine Vorschau (Einzelseite), „Auswählen“ zeigt es im Vollbild – mit ‹ › blätterst du zum vorigen oder nächsten Blatt. Das ausgewählte Blatt ist in der Liste türkis markiert. „2 Seiten“ und der doppelte Knopf „Blatt“ sind weg, der Knopf heißt jetzt „Notenblatt hinzufügen“, und der gelbe Hinweis ist verständlicher.",
        en: "Sheet Music: tap a sheet to open a preview (single page); “Select” shows it full screen – use ‹ › to flip to the previous or next sheet. The selected sheet is marked in teal in the list. “2 pages” and the duplicate “Sheet” button are gone, the button is now called “Add sheet”, and the yellow notice is easier to understand." },
      { de: "Hand Control: Übungen 3–24 wieder in der Liste „Danach“.",
        en: "Hand Control: exercises 3–24 are back in the “After that” list." },
      { de: "Die App heißt jetzt „Schlagfertig Control“. Auf der Startseite steht unter dem Logo nur noch „Control“.",
        en: "The app is now called “Schlagfertig Control”. On the home screen, only “Control” appears below the logo." },
      { de: "Rudiments: „Übepad“ heißt jetzt „Fokus-Mode“ – große Notation, weniger Bedienelemente. Eingeschaltet ist der Knopf türkis.",
        en: "Rudiments: “Pad” mode is now called “Focus mode” – large notation, fewer controls. The button turns teal when it is on." },
      { de: "Noten: Blätter bekommen eigene Namen und Tags. Du kannst suchen, nach Tags filtern und sortieren (neueste, älteste, Name A–Z).",
        en: "Sheet Music: give your sheets names and tags. You can search, filter by tag and sort (newest, oldest, name A–Z)." },
      { de: "Hand Control, Fokus-Mode: Wiederholungen wählst du jetzt an einem kleinen Drehrädchen. Beim Spielen steht groß über dem Kreis, die wievielte Wiederholung läuft (z. B. 2 / 4). In der letzten Wiederholung leuchtet die nächste Übung hell türkis auf.",
        en: "Hand Control, Focus mode: pick the number of repeats with a small scroll wheel. While playing, the current repeat is shown large above the dial (e.g. 2 / 4). During the last repeat, the next exercise lights up in light teal." },
      { de: "Hand Control startet jetzt immer groß: aktuelle Übung groß, die nächste als Vorschau darunter – der Schalter „Fokus + Preview“ entfällt. Frühere Übungen sind leicht unscharf, damit die aktuelle heraussticht. „Challenge“ heißt jetzt „Fokus-Mode“.",
        en: "Hand Control now always starts in the large view: the current exercise large, the next one below as a preview – the “Focus + Preview” switch is gone. Earlier exercises are slightly blurred so the current one stands out. “Challenge” is now called “Focus mode”." },
      { de: "Hand Control: neuer Modus „Fokus + Preview“ – die aktuelle Übung groß, die nächste klein darunter.",
        en: "Hand Control: new “Focus + Preview” mode – the current exercise large, the next one small below it." },
      { de: "Rhythmuspyramide: Du siehst jetzt die aktuelle und die nächste Stufe.",
        en: "Rhythm Pyramid: you now see the current and the next stage." },
      { de: "Click-Trainer: Tempo-Rad größer und mittig, „Erweitert“ öffnet sich als Fenster von unten.",
        en: "Click Trainer: bigger, centred tempo wheel; “Advanced” opens as a panel from the bottom." },
      { de: "Click-Trainer: Tempo-Schieberegler entfernt, Tempo nur noch über das Rad.",
        en: "Click Trainer: tempo slider removed, tempo is now set only with the wheel." },
      { de: "Tempo-Hinweis am Rad erscheint nur noch einmal statt in jedem Trainer.",
        en: "The dial tempo hint now shows only once instead of in every trainer." },
      { de: "Rudiments: Notenbild bei mehreren Rudiments korrigiert (u. a. #4, #13, #20, #27, #28, #29, #33 und die Rolls #13–#15).",
        en: "Rudiments: notation fixed for several rudiments (including #4, #13, #20, #27, #28, #29, #33 and rolls #13–#15)." },
      { de: "Hilfe zur Pyramide erklärt jetzt auch die Septole.",
        en: "The Rhythm Pyramid help now also explains the septuplet." },
    ],
  },
  {
    date: "2026-09-29",
    items: [
      { de: "Rudiments: Stickings besser lesbar, mehr Abstand vor dem Abschlag bei Ten und Eleven Stroke Roll.",
        en: "Rudiments: stickings easier to read, more space before the final stroke in the Ten and Eleven Stroke Roll." },
      { de: "Glasflächen und Hilfe-Fenster sind etwas durchsichtiger.",
        en: "Glass surfaces and help windows are a little more transparent." },
    ],
  },
  {
    date: "2026-09-28",
    items: [
      { de: "Hand Control: neuer Name auf der Startseite, im Titel und in der Übersicht.",
        en: "Hand Control: new name on the home screen, in the title and in the overview." },
      { de: "Rudiments: Gegensticking – viele Rudiments lassen sich auch mit links beginnend üben.",
        en: "Rudiments: opposite sticking – many rudiments can now be practised starting with the left hand." },
      { de: "Tempo-Rad: ruhige Mitte und Hinweis „Am Rand drehen“.",
        en: "Tempo wheel: calm centre and a “turn at the edge” hint." },
    ],
  },
  {
    date: "2026-09-27",
    items: [
      { de: "Die ganze App gibt es jetzt auch auf Englisch – umschalten mit der Flagge auf der Startseite.",
        en: "The whole app is now available in English – switch with the flag on the home screen." },
      { de: "Neues App-Logo „SPIELFERTIG‽ CONTROL“.",
        en: "New app logo “SPIELFERTIG‽ CONTROL”." },
      { de: "Kleines Extra: Tipp aufs Logo öffnet ein Metronom.",
        en: "Little extra: tap the logo to open a metronome." },
      { de: "Willkommensfenster mit persönlicher Begrüßung.",
        en: "Welcome window with a personal greeting." },
      { de: "Neue Glas-Optik für Flächen und Schaltflächen; Hilfe-Fenster erscheinen mittig.",
        en: "New glass look for surfaces and buttons; help windows now appear centred." },
      { de: "Rhythmuspyramide: neue Stufe Septole und größere Kacheln.",
        en: "Rhythm Pyramid: new septuplet stage and bigger tiles." },
      { de: "Click-Mixer zeigt Notensymbole statt Namen.",
        en: "The click mixer shows note symbols instead of names." },
    ],
  },
  {
    date: "2026-09-26",
    items: [
      { de: "Tempo-Rad: große Richtungspfeile beim Drehen, der Hebel folgt deinem Finger.",
        en: "Tempo wheel: large direction arrows while turning, the lever follows your finger." },
      { de: "Rhythmuspyramide: Stufen wählst du jetzt über Notengruppen; Einzählen wird groß eingeblendet.",
        en: "Rhythm Pyramid: pick stages via note groups; the count-in is shown large." },
    ],
  },
  {
    date: "2026-09-25",
    items: [
      { de: "Hand Control: feinere Noten, die aktuelle Übung bleibt oben stehen, entfernte Übungen sind unscharf.",
        en: "Hand Control: finer notes, the current exercise stays at the top, distant exercises are blurred." },
      { de: "Rudiments: Halte die untere Leiste gedrückt, um eine Vorschau der Noten zu sehen.",
        en: "Rudiments: press and hold the bottom bar to preview the notes." },
      { de: "Erste Übung: Start/Stop im Tempo-Rad.",
        en: "First Lesson: start/stop inside the tempo wheel." },
      { de: "Rhythmuspyramide: Tempo stellst du nur noch am Rad ein.",
        en: "Rhythm Pyramid: tempo is now set only with the wheel." },
    ],
  },
  {
    date: "2026-09-24",
    items: [
      { de: "Start/Stop sitzt jetzt in allen Trainern direkt im Metronom-Rad, das Rad ist größer.",
        en: "Start/stop now sits right inside the metronome wheel in every trainer, and the wheel is bigger." },
      { de: "Das Metronom bleibt unten am Bildschirm stehen.",
        en: "The metronome stays fixed at the bottom of the screen." },
      { de: "Tempo-Rad: gedrückt halten und drehen – innen grob, außen fein.",
        en: "Tempo wheel: press, hold and turn – coarse near the centre, fine at the edge." },
      { de: "Rhythmuspyramide: Stufen einzeln an- und abwählbar.",
        en: "Rhythm Pyramid: stages can be switched on and off individually." },
      { de: "Impressum und Datenschutz als eigene Seiten.",
        en: "Legal Notice and Privacy Policy as separate pages." },
      { de: "Größere Tippflächen und Umlaute überall.",
        en: "Bigger tap areas and proper German umlauts everywhere." },
    ],
  },
  {
    date: "2026-09-21",
    items: [
      { de: "Kurze Einführung beim ersten Öffnen jedes Bereichs.",
        en: "A short intro the first time you open each section." },
      { de: "Neu: „Erste Übung“ – eine geführte Mini-Lektion zum Einstieg.",
        en: "New: “First Lesson” – a short guided lesson to get started." },
      { de: "Drucken bleibt in der App, mit Live-Vorschau des A4-Blatts.",
        en: "Printing stays inside the app, with a live preview of the A4 sheet." },
      { de: "Hand Control: Challenge ab der aktuellen Übung, Einzählen 1 oder 2 Takte, Wischen zum Blättern.",
        en: "Hand Control: challenge from the current exercise, 1 or 2 bars count-in, swipe to browse." },
      { de: "Rudiments: Titel antippen öffnet die Auswahlliste.",
        en: "Rudiments: tap the title to open the list." },
      { de: "Besser auf dem Handy: nichts läuft mehr über den Rand, Querformat nutzbar.",
        en: "Better on phones: nothing spills over the edge, landscape works." },
    ],
  },
  {
    date: "2026-09-20",
    items: [
      { de: "Neu: Rhythmuspyramide – von Vierteln bis 32teln.",
        en: "New: Rhythm Pyramid – from quarter notes to 32nd notes." },
      { de: "Neu: Hand Control – 24 Übungen für Hand- und Stocktechnik.",
        en: "New: Hand Control – 24 exercises for hand and stick technique." },
      { de: "Neu: Noten – eigene Fotos und PDFs speichern und beim Üben aufschlagen.",
        en: "New: Sheet Music – save your own photos and PDFs and open them while practising." },
      { de: "Neu: erweiterter Click-Mixer mit Achteln, 16teln und Triolen.",
        en: "New: advanced click mixer with eighths, sixteenths and triplets." },
      { de: "Deine Einstellungen bleiben gespeichert.",
        en: "Your settings are remembered." },
      { de: "Größere Schrift fürs Handy.",
        en: "Larger text for phones." },
    ],
  },
  {
    date: "2026-09-19",
    items: [
      { de: "Snare-Klang in der Vorschau.",
        en: "Snare sound in the preview." },
      { de: "6/8-Takt mit passendem Click für die Diddle-Varianten.",
        en: "6/8 time with a matching click for the diddle variations." },
    ],
  },
  {
    date: "2026-09-18",
    items: [
      { de: "Tempo per Wischen am Metronom-Kreis; ±5-Tasten daneben.",
        en: "Change tempo by swiping around the metronome circle; ±5 buttons beside it." },
      { de: "Kurzhilfe hinter dem Fragezeichen.",
        en: "Quick help behind the question mark." },
    ],
  },
  {
    date: "2026-09-17",
    items: [
      { de: "Neu: Click-Trainer – das Tempo steigt automatisch.",
        en: "New: Click Trainer – the tempo rises automatically." },
      { de: "Schöneres, besser lesbares Notenbild.",
        en: "Nicer, more readable notation." },
    ],
  },
  {
    date: "2026-09-16",
    items: [
      { de: "Erste Version: alle 40 Rudiments mit Noten und Click.",
        en: "First version: all 40 rudiments with notation and click." },
    ],
  },
];

// Datum des neuesten Eintrags (für den „neu“-Punkt auf der Startseite).
export const CHANGELOG_LATEST = CHANGELOG[0]?.date || "";
