// Englisch: deutscher Originaltext → Übersetzung
export const EN = {
  // Home
  "Nochmal": "Again",
  "Loslegen": "Get started",
  "Erste Übung starten": "Start your first lesson",
  "Eine Minute mitklicken. Kein Fachwort nötig.": "One minute with the click. No jargon needed.",
  "Üben": "Practice",
  "40 Grundlagen für Technik, Kontrolle und Timing.": "40 essentials for technique, control and timing.",
  "Mit Notation, Click und Tempo.": "With notation, click and tempo.",
  "Öffnen": "Open",
  "Starttempo wählen. Tempo halten oder automatisch steigern.": "Pick a start tempo. Hold it or speed up automatically.",
  "4tel bis 32tel: Puls festigen, sauber zwischen Unterteilungen wechseln, Tempo trotz Dichte halten.": "Quarters to 32nds: lock in the pulse, switch cleanly between subdivisions, hold the tempo as it gets denser.",
  "Technik": "Technique",
  "Schwache Hand verbessern, saubere Wechsel üben, Tempo ohne Verspannungen halten.": "Strengthen your weak hand, practice clean switches, keep the tempo without tension.",
  "Eigene Blätter": "My sheet music",
  "Fotos und PDFs lokal ablegen und währenddessen aufschlagen.": "Keep photos and PDFs on your device and open them while you play.",
  // Titel
  "Erste Übung": "First Lesson",
  "Click-Trainer": "Click Trainer",
  "Rhythmuspyramide": "Rhythm Pyramid",
  "Noten": "Sheet Music",
  "Impressum": "Legal Notice",
  "Datenschutz": "Privacy Policy",
  "Neuigkeiten": "What’s new",
  "neu": "new",
  "Was sich in der App geändert hat – das Neueste zuerst.": "What has changed in the app – newest first.",
  // Kopfleiste
  "Zurück": "Back",
  "Drucken": "Print",
  "Blatt": "Sheet",
  "Fokus-Mode": "Focus mode",
  "Notation groß, weniger Bedienelemente.": "Large notation, fewer controls.",
  // Logo-Metronom
  "Logo: Metronom öffnen": "Logo: open metronome",
  "Metronom schließen": "Close metronome",
  "5 BPM langsamer": "5 BPM slower",
  "5 BPM schneller": "5 BPM faster",
  // Metronom-Kreis
  "TIPP LINKS": "TURN LEFT",
  "= LANGSAMER": "= SLOWER",
  "TIPP RECHTS": "TURN RIGHT",
  "= SCHNELLER": "= FASTER",
  "Tipp = Start/Stop. Am Rand drehen ändert das Tempo. Außen feiner.": "Tap = start/stop. Turn at the edge to change the tempo. Finer further out.",
  "Metronom starten. Halten und drehen ändert das Tempo.": "Start metronome. Hold and turn to change the tempo.",
  "Metronom stoppen. Halten und drehen ändert das Tempo.": "Stop metronome. Hold and turn to change the tempo.",
  "Tempo drehen": "Turn the tempo",
  "Am Rand drehen · außen feiner": "Turn at the edge · finer outside",
  "Am Rand drehen. Rechts schneller, links langsamer. Außen feiner.": "Turn at the edge. Right faster, left slower. Finer further out.",
  // Kurzhilfe
  "Kurzhilfe": "Quick help",
  "Kurz anschauen": "Quick look",
  "Kurz": "Quick help",
  "Einmalig beim ersten Öffnen — danach jederzeit über ?": "Shown once on first open — after that, anytime via ?",
  "Verstanden": "Got it",
  "Schließen": "Close",
  // Begrüßung
  "Willkommen bei Schlagfertig Control! 🥁": "Welcome to Schlagfertig Control! 🥁",
  "Hallo {name}, willkommen bei Schlagfertig Control! 🥁": "Hi {name}, welcome to Schlagfertig Control! 🥁",
  "Schön, dass du dabei bist und die App testest. Starte am besten mit „Erste Übung“ – das dauert nur eine Minute. Über das „?“ oben rechts findest du überall Hilfe. Ich freue mich über jede Rückmeldung!": "Great to have you here testing the app. Tap “Start your first lesson” – it only takes a minute. Tap “?” at the top right for help anywhere. I'd love to hear your feedback!",
  "Los geht's": "Let's go",
  "40 PAS-Übungen. Notation lesen, Click hören, Tempo halten.": "40 PAS exercises. Read the notation, hear the click, hold the tempo.",
  "Metronom: Tempo steigern oder halten. ‚Erweitert‘ = Click-Mixer.": "Metronome: speed up or hold the tempo. ‘Advanced’ = click mixer.",
  "Subdivisionen auf und ab, 4tel bis 32tel.": "Subdivisions up and down, quarters to 32nds.",
  "24 Single-Beat-Nummern. Fokus-Mode spielt 1–24 durch.": "24 single-beat exercises. Focus mode plays 1–24 in a row.",
  "Eigene Fotos/PDFs, nur auf diesem Gerät. Antippen = Vorschau, ‚Auswählen‘ = Vollbild.": "Your own photos/PDFs, only on this device. Tap = preview, ‘Select’ = full screen.",
  "Kreis": "Dial",
  "Tippen = Start/Stop. Halten + drehen = Tempo.": "Tap = start/stop. Hold + turn = tempo.",
  "Metronom unten": "Metronome (bottom)",
  "Tippen = Start/Stop. Halten + drehen: rechtsrum schneller.": "Tap = start/stop. Hold + turn: clockwise = faster.",
  "Radius": "Radius",
  "Innen grob, außen fein, auch über den Ring hinaus. −5/+5 daneben.": "Coarse near the center, fine further out, even beyond the ring. −5/+5 next to it.",
  "Nav unten": "Bottom nav",
  "‹ › tippen = vor/zurück. Wischen springt mehrere. Halten öffnet das Zahlenrad.": "Tap ‹ › = next/previous. Swipe to skip several. Hold to open the number wheel.",
  "Titel": "Title",
  "‚Rudiment wählen‘ + ▾ öffnet die komplette Liste.": "‘Choose rudiment’ + ▾ opens the full list.",
  "Hören": "Sound",
  "Snare, L/R oder Nur Click — Umschalter über dem Kreis.": "Snare, L/R or click only — switch above the dial.",
  "Erweitert": "Advanced",
  "‚Erweitert‘ unter dem Kreis öffnet den Click-Mixer von unten. Mixer für Viertel, Offbeat, 16tel, Triolen, Beat und Master. Der Click läuft dabei weiter.": "‘Advanced’ below the dial opens the click mixer from the bottom. Mixer for quarters, offbeats, 16ths, triplets, beat and master. The click keeps running.",
  "Tippen = Start/Stop. Am Rand drehen: rechtsrum schneller.": "Tap = start/stop. Turn at the edge: clockwise = faster.",
  "Modi": "Modes",
  "Tempo halten oder steigern (alle X Sekunden +Y BPM).": "Hold or increase the tempo (every X seconds +Y BPM).",
  "Tippen = Start/Stop. Halten + drehen = Tempo, innen grob, außen fein, auch über den Ring hinaus. −5/+5 daneben.": "Tap = start/stop. Hold + turn = tempo, coarse near the center, fine further out, even beyond the ring. −5/+5 next to it.",
  "Stufen": "Levels",
  "4tel → 8tel → 8tel-Triole → 16tel → Quintole → 16tel-Sextole → Septole → 32tel. Tippen schaltet einzeln an/aus, eine bleibt immer an.": "Quarters → 8ths → 8th triplets → 16ths → quintuplets → 16th sextuplets → septuplets → 32nds. Tap to switch each on/off; one always stays on.",
  "Takte": "Bars",
  "1, 2 oder 4 Takte pro Stufe, immer im 4/4.": "1, 2 or 4 bars per level, always in 4/4.",
  "Tippen = Start/Stop. Drehen = Tempo, innen grob, außen fein. −5/+5 daneben.": "Tap = start/stop. Turn = tempo, coarse near the center, fine further out. −5/+5 next to it.",
  "‹ › oder wischen. Halten öffnet das Rad, Vorschau = erste 8 Achtel.": "‹ › or swipe. Hold to open the wheel; preview = first 8 eighths.",
  "Liste": "List",
  "Die aktuelle Nummer groß, darunter die nächste als Vorschau – antippen = weiter. Nach oben scrollen zeigt frühere Nummern, leicht unscharf.": "The current exercise large, the next one below as a preview – tap it to move on. Scroll up for earlier exercises, slightly blurred.",
  "1–24 durchspielen. Wiederholungen = komplette Übung (beide Takte). Einzählen nur am Start, nicht zwischen den Nummern.": "Play through 1–24. Repeats = the whole exercise (both bars). Count-in only at the start, not between exercises.",
  "Lokal": "Local",
  "Dateien bleiben im Browser dieses Geräts. Kein Upload in die Cloud.": "Files stay in this device’s browser. Nothing is uploaded to the cloud.",
  "Format": "Format",
  "Foto oder PDF, bis 12 MB.": "Photo or PDF, up to 12 MB.",
  "In Rudiments u. a. über Blatt öffnen — Playback läuft weiter.": "Open via Sheet in Rudiments and other trainers — playback keeps running.",
  // Erste Übung
  "Fertig": "Done",
  "Eine Minute gehalten.": "You held it for a minute.",
  "Als Nächstes: eine einfache Figur mit rechts/links — oder die Hände einzeln sauber wechseln.": "Next up: a simple right/left pattern — or clean switches between your hands.",
  "Als Nächstes": "Next up",
  "Kleine Standard-Übungen. Fang mit Nr. 1 an: abwechselnd rechts und links.": "Short standard exercises. Start with no. 1: alternate right and left.",
  "Oder": "Or",
  "24 kurze Handwechsel. Tempo bleibt gleich, nur die Folge ändert sich.": "24 short hand patterns. The tempo stays the same, only the sticking changes.",
  "Zurück zur Übersicht": "Back to overview",
  "Eine Minute im Puls bleiben": "Stay in the pulse for one minute",
  "Du hörst einen gleichmäßigen Klick — 80 Schläge pro Minute, das ist ein ruhiges Gehtempo. Bei jedem Klick ein Schlag auf dem Pad. Nicht schneller werden.": "You’ll hear a steady click — 80 beats per minute, a relaxed walking pace. Play one stroke on the pad with every click. Don’t speed up.",
  "Läuft": "Running",
  "Bleib am Pad. Jeder Klick = ein Schlag.": "Stay on the pad. Every click = one stroke.",
  "Sekunden": "seconds",
  "Überspringen": "Skip",
  // Trainer: gemeinsam
  "1 Takt": "1 bar",
  "2 Takte": "2 bars",
  "{n} T.": "{n} bars",
  "Einzählen": "Count-in",
  // Click-Trainer
  "Click starten. Alle paar Sekunden wird das Tempo angehoben — Du bleibst am Pad.": "Start the click. Every few seconds the tempo goes up — you stay on the pad.",
  "Gleichmäßiges Tempo halten. BPM am Kreis drehen oder ±5.": "Hold a steady tempo. Turn the dial or tap ±5 to set the BPM.",
  "Gleichmäßiges Tempo. Kreis drehen oder ±5.": "Steady tempo. Turn the dial or tap ±5.",
  "Tempo halten": "Hold tempo",
  "Tempo steigern": "Speed up",
  "Einstellung": "Settings",
  "Alle": "Every",
  "um": "faster by",
  "BPM schneller": "BPM",
  "bis": "up to",
  "Beispiel: Start {start}, alle {every}s +{step}, Ziel {cap}.": "Example: start {start}, every {every}s +{step}, target {cap}.",
  "Fester Puls bei {bpm} BPM. Drehen ändert das Tempo live.": "Steady pulse at {bpm} BPM. Turning changes the tempo live.",
  "Click-Mixer": "Click mixer",
  "Ziel": "Target",
  "Sek. bis +{step}": "sec to +{step}",
  "App im Hintergrund — der Click kann pausieren. Zurückkommen und ggf. neu starten.": "App in the background — the click may pause. Come back and restart if needed.",
  "Metronom": "Metronome",
  "Normal": "Normal",
  "Jede Zeile ist eine eigene Click-Ebene, der Lautsprecher regelt alle zusammen.": "Each row is its own click layer; the speaker controls them all.",
  "Änderungen gelten sofort, der Click läuft weiter.": "Changes apply instantly; the click keeps running.",
  "Viertel": "Quarter notes",
  "Grundpuls 1 2 3 4": "basic pulse 1 2 3 4",
  "Offbeat": "Offbeat",
  "das „und“ dazwischen": "the “and” in between",
  "16tel e/a": "16th notes e/a",
  "zwischen den Achteln": "between the 8ths",
  "Triolen": "Triplets",
  "2 und 3, 1 bleibt Viertel": "2 and 3; 1 stays a quarter",
  "BEAT": "BEAT",
  "betonte 1, anderer Klang": "accented 1, different sound",
  "Master": "Master",
  "Lautstärke aller Ebenen": "volume of all layers",
  // Rhythmuspyramide
  "Stufen wählen · immer 4/4.": "Choose levels · always 4/4.",
  "4tel": "Quarter notes",
  "8tel": "Eighth notes",
  "8tel-Triole": "Eighth-note triplets",
  "16tel": "16th notes",
  "Quintole": "Quintuplets",
  "16tel-Sextole": "16th-note sextuplets",
  "Septole": "Septuplets",
  "32tel": "32nd notes",
  "auf": "up",
  "ab": "down",
  "auf+ab": "up+down",
  "Takt übrig": "bar left",
  "Takte übrig": "bars left",
  "Pyramide fertig.": "Pyramid done.",
  "Jetzt": "Now",
  "Letzte Stufe": "Last level",
  "danach fertig": "then done",
  "Stufe {i}/{n}": "Level {i}/{n}",
  // Hand Control
  "Letzte Übung": "Last exercise",
  "Nr. {n}": "No. {n}",
  "Nummer {n}": "Exercise {n}",
  "DAVOR": "PREVIOUS",
  "Danach": "After that",
  "Wiederholungen": "Repeats",
  "Wiederholung": "Repeat",
  "Wdh.": "Reps",
  "Wiederholung {n} von {m}": "Repeat {n} of {m}",
  "Aus": "Off",
  "Bis Nr. 24 gehalten (ab Nr. {n}).": "Held through No. 24 (from No. {n}).",
  // Rudiments
  "Rudiment wählen": "Choose rudiment",
  "Frei": "Free",
  "8 Loops": "8 loops",
  "16 Loops": "16 loops",
  "2 Min": "2 min",
  "Ziel gehalten — weiter so.": "Goal reached — keep it up.",
  "Aktueller Schlag oben markiert · R blau · L rot": "Current beat marked on top · R blue · L red",
  "Nur Click": "Click only",
  // Noten (Archiv)
  "Tipp auf ein Blatt": "Tap a sheet",
  "Archiv auf diesem Gerät nicht verfügbar (privater Modus?).": "Storage isn’t available on this device (private mode?).",
  "Gespeichert auf diesem Gerät. Kopie extra in Dateien oder Cloud legen.": "Saved on this device. Keep a separate copy in Files or the cloud.",
  "Konnte das Blatt nicht speichern.": "Couldn’t save the sheet.",
  "Blatt vom Gerät löschen?": "Delete this sheet from the device?",
  "Blatt gelöscht.": "Sheet deleted.",
  "Name": "Name",
  "Name geändert.": "Name changed.",
  "Nur lokal": "Local only",
  "Liegt nur in diesem Browser. Gerätewechsel, Cache leeren oder App neu installieren kann alles löschen. Backup: Original-PDF/Foto extra in Dateien, Mail oder Cloud behalten.": "Stored only in this browser. Switching devices, clearing the cache or reinstalling the app can delete everything. Backup: keep the original PDF/photo in Files, email or the cloud.",
  "Hinzufügen": "Add",
  "Noch keine Blätter. Mit „Hinzufügen“ Foto oder PDF ablegen.": "No sheets yet. Tap “Add” to store a photo or PDF.",
  "Foto": "Photo",
  "Löschen": "Delete",
  "Archiv nicht verfügbar": "Storage not available",
  "abgebrochen": "cancelled",
  "Keine Datei.": "No file.",
  "Maximal 12 MB pro Blatt.": "Max. 12 MB per sheet.",
  "Nur Foto oder PDF.": "Photo or PDF only.",
  // Noten: bisher fehlende Übersetzungen (Archiv-Ansicht)
  "Deine Noten bleiben auf diesem Gerät": "Your sheet music stays on this device",
  "Fotos und PDFs werden nur hier im Browser gespeichert. Auf einem anderen Gerät siehst du sie nicht, und wenn du die Browserdaten löschst, sind sie weg. Bewahre deine Originale also zusätzlich woanders auf.": "Photos and PDFs are only saved here in your browser. You won’t see them on another device, and if you clear your browser data, they’re gone. So keep your originals somewhere else as well.",
  "Gespeichert. Extra-Kopie in Dateien oder Cloud legen.": "Saved. Keep an extra copy in Files or the cloud.",
  "Speichern fehlgeschlagen.": "Saving failed.",
  "Hier nicht verfügbar (privater Modus?).": "Not available here (private mode?).",
  "Gelöscht.": "Deleted.",
  "Noch nichts hier. Foto oder PDF hinzufügen.": "Nothing here yet. Add a photo or PDF.",
  // Noten: Vorschau, Auswahl, Vollbild
  "Notenblatt hinzufügen": "Add sheet",
  "Einzelseite": "Single page",
  "Auswählen": "Select",
  "Ausgewählt": "Selected",
  "Vorheriges Blatt": "Previous sheet",
  "Nächstes Blatt": "Next sheet",
  // Noten: Zoom
  "Vergrößern": "Zoom in",
  "Verkleinern": "Zoom out",
  "Ganze Seite zeigen": "Show whole page",
  "Ganz": "Fit",
  "Vorherige Seite": "Previous page",
  "Nächste Seite": "Next page",
  "Seite {n}/{m}": "Page {n}/{m}",
  "PDF konnte nicht angezeigt werden.": "The PDF could not be displayed.",
  "Zoomen": "Zoom",
  "Zwei Finger oder Doppeltipp zoomen bis 5×, gezoomt mit einem Finger verschieben. − / + / „Ganz“ unten; „Ganz“ zeigt wieder die ganze Seite.": "Pinch or double-tap to zoom up to 5×; when zoomed, drag with one finger. Use − / + / “Fit” at the bottom; “Fit” shows the whole page again.",
  // Noten: WA-22 Name + Tags, Suche, Filter, Sortierung
  "Name & Tags": "Name & tags",
  "Name & Tags bearbeiten: {name}": "Edit name & tags: {name}",
  "Tags": "Tags",
  "Tag hinzufügen": "Add tag",
  "Tag entfernen: {tag}": "Remove tag: {tag}",
  "Höchstens {n} Tags.": "At most {n} tags.",
  "Vorschläge": "Suggestions",
  "Optional, z. B. Paradiddle, Fills, Groove.": "Optional, e.g. paradiddle, fills, groove.",
  "Abbrechen": "Cancel",
  "Name und Tags gespeichert.": "Name and tags saved.",
  "Name/Tag suchen": "Search name/tag",
  "Suchen": "Search",
  "Sortieren": "Sort",
  "Neueste zuerst": "Newest first",
  "Älteste zuerst": "Oldest first",
  "Name A–Z": "Name A–Z",
  "Nach Tag filtern": "Filter by tag",
  "arch|Alle": "All",
  "{n} von {m}": "{n} of {m}",
  "Nichts gefunden.": "Nothing found.",
  "Filter zurücksetzen": "Reset filters",
  // Kurzhilfe Noten
  "Nur hier": "Only here",
  "Fotos und PDFs bleiben in diesem Browser, nichts wird hochgeladen. Auf einem anderen Gerät sind sie nicht da; Browserdaten löschen entfernt sie.": "Photos and PDFs stay in this browser; nothing is uploaded. They aren’t on your other devices, and clearing your browser data removes them.",
  "Foto oder PDF, maximal 12 MB.": "Photo or PDF, max. 12 MB.",
  "Pro Blatt Name und Tags vergeben. Oben suchen, nach Tag filtern, sortieren.": "Give each sheet a name and tags. Search at the top, filter by tag, sort.",
  "Ansehen": "View",
  "Blatt antippen öffnet die Vorschau (Einzelseite). ‚Auswählen‘ markiert es türkis und zeigt es im Vollbild.": "Tap a sheet to open the preview (single page). ‘Select’ marks it in teal and shows it full screen.",
  "Blättern": "Flip",
  "Im Vollbild mit ‹ › (oder Wischen) zum vorigen bzw. nächsten Blatt der Liste.": "In full screen, use ‹ › (or swipe) to go to the previous or next sheet in the list.",
  "Im Vollbild mit ‹ › (oder Wischen, wenn nicht gezoomt) zum vorigen bzw. nächsten Blatt der Liste.": "In full screen, use ‹ › (or swipe when not zoomed) to go to the previous or next sheet in the list.",
  // Drucken
  "Druckvorschau": "Print preview",
  "Vorschau · erste Seite": "Preview · first page",
  "Übungen anhaken — die Seite baut sich hier auf.": "Tick exercises — the page builds up here.",
  "Rudiments drucken": "Print rudiments",
  "Aktuelles Blatt: {name}": "Current sheet: {name}",
  "Übung": "Exercise",
  "Auswahl: 1 Übung": "Selected: 1 exercise",
  "Auswahl: {n} Übungen": "Selected: {n} exercises",
  "Vorschau unten.": "Preview below.",
  "{n} / Seite": "{n} / page",
  "print|Alle": "All",
  "Nur aktuelles Blatt": "Current sheet only",
  "jetzt": "now",
  "Speichern": "Save",
  "Teilen": "Share",
  "Vom Home-Bildschirm gibt es keinen Systemdruck. Speichern legt ein PNG ab.": "There’s no system printing from the home screen app. Save stores a PNG.",
  "Drucken öffnet den Systemdialog. Die App sagt danach Bescheid.": "Print opens the system dialog. The app lets you know afterwards.",
  "PNG gespeichert — Dateien / Downloads prüfen.": "PNG saved — check Files / Downloads.",
  "Speichern abgebrochen.": "Saving cancelled.",
  "Blatt wird erzeugt…": "Creating sheet…",
  "Teilen wird vorbereitet…": "Preparing to share…",
  "PNG wird erzeugt…": "Creating PNG…",
  "Keine Notation zum Export.": "No notation to export.",
  "Home-Bildschirm: Systemdruck fehlt. Blatt als PNG gespeichert.": "Home screen app: no system printing. Sheet saved as PNG.",
  "Druckdialog geöffnet. Fertig? Oben auf Zurück.": "Print dialog opened. Done? Tap Back at the top.",
  "Druck blockiert oder fehlgeschlagen — PNG gespeichert.": "Printing blocked or failed — PNG saved.",
  "Geteilt.": "Shared.",
  "Teilen nicht verfügbar — PNG gespeichert.": "Sharing not available — PNG saved.",
  "Teilen abgebrochen.": "Sharing cancelled.",
  "Konnte das Blatt nicht erzeugen. Bitte erneut versuchen.": "Couldn’t create the sheet. Please try again.",
  // Rechtliches
  "Weitere Angaben": "More information",
  "Zum Impressum": "Go to Legal Notice",
  "Zur Datenschutzerklärung": "Go to Privacy Policy",
  // index.html
  "Rudiments und Grooves üben. Zeit für guten Sound.": "Practice rudiments and grooves. Time for great sound.",
};
