// Englisch: deutscher Originaltext → Übersetzung
export const EN = {
  // Home
  "Nochmal": "Again",
  "Loslegen": "Get started",
  "Erste Übung starten": "Start your first lesson",
  "Leg einfach los: Spiel eine Minute zum Click – ganz ohne Vorwissen.": "Just jump in: play along with the click for one minute – no prior knowledge needed.",
  "Üben": "Practice",
  "Meistere 40 Grundlagen für Technik, Kontrolle und Timing.": "Master 40 essentials for technique, control and timing.",
  "Mit Notation, Click und Tempo.": "With notation, click and tempo.",
  "Öffnen": "Open",
  "Dein Tempo, dein Groove: Halte es sicher oder steigere es Schritt für Schritt.": "Your tempo, your groove: hold it steady or raise it step by step.",
  "Von 4teln bis 32teln: Festige deinen Puls und wechsle sauber zwischen den Unterteilungen.": "From quarters to 32nds: strengthen your pulse and switch cleanly between subdivisions.",
  "Technik": "Technique",
  "Stärke deine schwache Hand, übe saubere Wechsel und halte das Tempo ganz locker.": "Strengthen your weak hand, practise clean switches and keep the tempo relaxed.",
  "Eigene Blätter": "My sheet music",
  "Hab deine Noten immer dabei: Speichere Fotos und PDFs, schlag sie beim Üben auf und zoom hinein.": "Keep your sheet music with you: save photos and PDFs, open them while you practise and zoom in.",
  // Titel
  "Erste Übung": "First Lesson",
  "Click-Trainer": "Click Trainer",
  "Rhythmuspyramide": "Rhythm Pyramid",
  "Noten": "Sheet Music",
  "Meine Grooves": "My grooves",
  "Eigenen Groove bauen und üben. Eintippen nur quer, hochkant siehst du den Rhythmus.": "Build and practise your own groove. Enter it in landscape, portrait shows the rhythm.",
  "Erstellen": "Create",
  "Nur quer: Hi-Hat, Snare und Bass antippen. Eine Zeile wird aktiv, oben rechts gelten 1, + und e a. Taktzahl 1–4 sitzt neben der Vorschau.": "Landscape only: tap hi-hat, snare and bass. A row becomes active, 1, + and e a apply at the top right. Bar count 1–4 sits beside the preview.",
  "Hochkant": "Portrait",
  "Nur die Notation. Zum Eintippen das Gerät quer drehen.": "Notation only. Turn the device sideways to enter notes.",
  "Speichern als…": "Save as…",
  "Beides": "Both",
  "Bearbeiten": "Edit",
  "Zum Eintippen das Handy quer drehen. Hochkant siehst du nur den Rhythmus.": "Turn your phone sideways to enter notes. In portrait you only see the rhythm.",
  "Fragt den Namen ab. Der Groove bleibt auf diesem Gerät.": "Asks for the name. The groove stays on this device.",
  "Üben": "Practise",
  "Nur Click, Playback oder Beides. Der Click blinkt auf den vollen Zählzeiten. Dial wie überall: tippen startet, drehen ändert das Tempo.": "Click only, playback or both. The click flashes on the beat. Dial as everywhere: tap to start, turn to change the tempo.",

  "Groove": "Groove",
  "Bau deinen eigenen Groove, gib ihm einen Namen und üb ihn mit der Dial, bis er sitzt.": "Build your own groove, give it a name and practise it with the dial until it locks in.",
  "Erstellen": "Build",
  "Üben": "Practice",
  "Archiv": "Archive",
  "Neuer Rhythmus": "New rhythm",
  "Name": "Name",
  "z. B. Rock-Grund": "e.g. basic rock",
  "Takt": "Bar",
  "Takt kopieren": "Copy bar",
  "leer": "clear",
  "Speichern": "Save",
  "Nur auf diesem Gerät gespeichert. Bei Browser- oder Gerätewechsel kann das Archiv verloren gehen.": "Saved on this device only. The archive can be lost if you switch browser or device.",
  "Noch nichts gespeichert.": "Nothing saved yet.",
  "Löschen": "Delete",
  "Ohne Namen": "Untitled",
  "Vorheriger Takt": "Previous bar",
  "Nächster Takt": "Next bar",
  "Groove löschen?": "Delete groove?",
  "„{name}“ wird von diesem Gerät gelöscht.": "“{name}” will be deleted from this device.",
  "Groove „{name}“ löschen": "Delete groove “{name}”",
  "Ride": "Ride",
  "Offen": "Open",
  "Bass": "Bass",
  "Rhythmus": "Rhythm",
  "Impressum": "Legal Notice",
  "Datenschutz": "Privacy Policy",
  "Neuigkeiten": "What’s new",
  "Neu: Unter ‚Neuigkeiten‘ siehst du, was sich in der App geändert hat.": "New: ‘What’s new’ shows what has changed in the app.",
  "Später": "Later",
  "neu": "new",
  "Was sich in Schlagfertig‽ geändert hat – das Neueste zuerst.": "What has changed in Schlagfertig‽ – newest first.",
  // Kopfleiste
  "Zurück": "Back",
  "Drucken": "Print",
  "Blatt": "Sheet",
  "Fokus-Mode": "Focus mode",
  "Lexikon": "Glossary",
  "Nachschlagen": "Look up",
  "Downbeat, Flam, Groove: Schlag nach, was dahintersteckt – von A bis Z.": "Downbeat, flam, groove: look up what they mean – from A to Z.",
  "Begriff suchen": "Search a term",
  "Buchstaben": "Letters",
  "Kein Treffer.": "No matches.",
  "Zu diesem Rudiment liegt noch keine Info.": "There is no info for this rudiment yet.",
  "Kurze Erklärungen zum Nachschlagen – tipp einen Begriff an.": "Short explanations to look up – tap a term.",
  "Info": "Info",
  "Notation": "Notation",
  "Was es ist": "What it is",
  "Name": "Name",
  "Herkunft": "Origin",
  "Wofür": "What it is for",
  "binär": "Straight",
  "ternär": "Triplets",
  "Raster": "Grid",
  "Notation groß, weniger Bedienelemente.": "Large notation, fewer controls.",
  // Logo-Metronom
  "Logo: Metronom öffnen": "Logo: open metronome",
  "Metronom schließen": "Close metronome",
  "5 BPM langsamer": "5 BPM slower",
  "5 BPM schneller": "5 BPM faster",
  // Kontakt-Knöpfe (Footer)
  "Kontakt": "Contact",
  "WhatsApp schreiben": "Message on WhatsApp",
  "E-Mail schreiben": "Send email",
  // Metronom-Kreis
  "TIPP LINKS": "TURN LEFT",
  "= LANGSAMER": "= SLOWER",
  "TIPP RECHTS": "TURN RIGHT",
  "= SCHNELLER": "= FASTER",
  "Tipp = Start/Stop. Zum Einstellen am Ring drehen.": "Tap = start/stop. Turn the ring to adjust.",
  "Metronom starten. Halten und drehen ändert das Tempo.": "Start metronome. Hold and turn to change the tempo.",
  "Metronom stoppen. Halten und drehen ändert das Tempo.": "Stop metronome. Hold and turn to change the tempo.",
  "Tempo einstellen": "Set the tempo",
  "Zum Einstellen drehen": "Turn to adjust",
  "Zum Einstellen am Ring drehen: rechts herum schneller, links herum langsamer. Mit −5/+5 und −10/+10 springst du in Schritten. Mitte antippen startet und stoppt.": "Turn the ring to adjust: clockwise is faster, anticlockwise slower. −5/+5 and −10/+10 jump in steps. Tap the centre to start and stop.",
  "LANGSAMER": "SLOWER",
  "SCHNELLER": "FASTER",
  "MITTE ANTIPPEN = START / STOP": "TAP CENTRE = START / STOP",
  "{n} BPM langsamer": "{n} BPM slower",
  "{n} BPM schneller": "{n} BPM faster",
  // Kurzhilfe
  "Kurzhilfe": "Quick help",
  "Kurz anschauen": "Quick look",
  "Kurz": "Quick help",
  "Einmalig beim ersten Öffnen — danach jederzeit über ?": "Shown once on first open — after that, anytime via ?",
  "Verstanden": "Got it",
  "Schließen": "Close",
  // Begrüßung
  "Willkommen bei Schlagfertig‽ 🥁": "Welcome to Schlagfertig‽ 🥁",
  "Hallo {name}, willkommen bei Schlagfertig‽ 🥁": "Hi {name}, welcome to Schlagfertig‽ 🥁",
  "Drums lernen – Schlag für Schlag": "Learn drums – beat by beat",
  "Hallo mein Schatz! ❤️": "Hi my darling! ❤️",
  "Schön, dass du dabei bist und die App testest. Starte am besten mit „Erste Übung“ – das dauert nur eine Minute. Über das „?“ oben rechts findest du überall Hilfe. Ich freue mich über jede Rückmeldung!": "Great to have you here testing the app. Tap “Start your first lesson” – it only takes a minute. Tap “?” at the top right for help anywhere. I'd love to hear your feedback!",
  "Los geht's": "Let's go",
  "40 Grundlagen für Technik, Kontrolle und Timing. Mit Notation, Click und Tempo.": "40 essentials for technique, control and timing. With notation, click and tempo.",
  "Metronom: Tempo steigern oder halten. ‚Erweitert‘ = Click-Mixer.": "Metronome: speed up or hold the tempo. ‘Advanced’ = click mixer.",
  "Subdivisionen auf und ab, 4tel bis 32tel.": "Subdivisions up and down, quarters to 32nds.",
  "24 Handübungen. Fokus-Mode spielt 1⁠–⁠24 durch.": "24 hand exercises. Focus mode plays 1⁠–⁠24 in a row.",
  "Eigene Fotos/PDFs, nur auf diesem Gerät. Antippen = Vorschau, ‚Auswählen‘ = Vollbild mit Zoom.": "Your own photos/PDFs, only on this device. Tap = preview, ‘Select’ = full screen with zoom.",
  "Kreis": "Dial",
  "Tippen = Start/Stop. Halten + drehen = Tempo.": "Tap = start/stop. Hold + turn = tempo.",
  "Metronom unten": "Metronome (bottom)",
  "Tippen = Start/Stop. Halten + drehen: rechtsrum schneller.": "Tap = start/stop. Hold + turn: clockwise = faster.",
  "Tasten": "Buttons",
  "−5/+5 und −10/+10 neben dem Kreis springen in Schritten.": "−5/+5 and −10/+10 next to the dial jump in steps.",
  "Nav unten": "Bottom nav",
  "‹ › tippen = vor/zurück. Wischen springt mehrere. Halten öffnet das Zahlenrad.": "Tap ‹ › = next/previous. Swipe to skip several. Hold to open the number wheel.",
  "Titel": "Title",
  "‚Rudiment wählen‘ + ▾ öffnet die komplette Liste.": "‘Choose rudiment’ + ▾ opens the full list.",
  "Ziel & Klang": "Goal & sound",
  "Über dem Kreis: Ziel (frei, 8 oder 16 Loops, 2 Min) und Klang (Snare, Tom / Snare, Nur Click).": "Above the dial: goal (free, 8 or 16 loops, 2 min) and sound (snare, tom / snare, click only).",
  "Erweitert": "Advanced",
  "‚Erweitert‘ unter dem Kreis öffnet den Click-Mixer von unten. Mixer für Viertel, Offbeat, 16tel, Triolen, Beat und Master. Der Click läuft dabei weiter.": "‘Advanced’ below the dial opens the click mixer from the bottom. Mixer for quarters, offbeats, 16ths, triplets, beat and master. The click keeps running.",
  "Tippen = Start/Stop. Am Ring drehen: rechtsrum schneller.": "Tap = start/stop. Turn the ring: clockwise = faster.",
  "Modi": "Modes",
  "Tempo halten oder steigern (alle X Sekunden +Y BPM).": "Hold or increase the tempo (every X seconds +Y BPM).",
  "Tippen = Start/Stop. Halten + drehen = Tempo. −5/+5 und −10/+10 daneben.": "Tap = start/stop. Hold + turn = tempo. −5/+5 and −10/+10 next to it.",
  "Stufen": "Levels",
  "4tel → 8tel → 8tel-Triole → 16tel → Quintole → 16tel-Sextole → Septole → 32tel. Tippen schaltet einzeln an/aus, eine bleibt immer an.": "Quarters → 8ths → 8th triplets → 16ths → quintuplets → 16th sextuplets → septuplets → 32nds. Tap to switch each on/off; one always stays on.",
  "Takte": "Bars",
  "1, 2 oder 4 Takte pro Stufe, immer im 4/4.": "1, 2 or 4 bars per level, always in 4/4.",
  "Tippen = Start/Stop. Drehen = Tempo. −5/+5 und −10/+10 daneben.": "Tap = start/stop. Turn = tempo. −5/+5 and −10/+10 next to it.",
  "‹ › oder wischen. Halten öffnet das Rad, Vorschau = erste 8 Achtel.": "‹ › or swipe. Hold to open the wheel; preview = first 8 eighths.",
  "Liste": "List",
  "Die aktuelle Nummer groß, darunter die nächste als Vorschau – antippen = weiter. Nach oben scrollen zeigt frühere Nummern, leicht unscharf.": "The current exercise large, the next one below as a preview – tap it to move on. Scroll up for earlier exercises, slightly blurred.",
  "1–24 durchspielen. Wiederholungen = komplette Übung (beide Takte). Einzählen nur am Start, nicht zwischen den Nummern.": "Play through 1–24. Repeats = the whole exercise (both bars). Count-in only at the start, not between exercises.",
  "Lokal": "Local",
  "Dateien bleiben im Browser dieses Geräts. Kein Upload in die Cloud.": "Files stay in this device’s browser. Nothing is uploaded to the cloud.",
  "Format": "Format",
  "Foto oder PDF, bis 12 MB.": "Photo or PDF, up to 12 MB.",
  "In Rudiments u. a. über Blatt öffnen — Playback läuft weiter.": "Open via Sheet in Rudiments and other trainers — playback keeps running.",
  // Erste Übung
  "Fertig": "Done",
  "Eine Minute gehalten.": "You held it for a minute.",
  "Als Nächstes: eine einfache Figur mit rechts/links — oder die Hände einzeln sauber wechseln.": "Next up: a simple right/left pattern — or clean switches between your hands.",
  "Als Nächstes": "Next up",
  "Kleine Standard-Übungen. Fang mit Nr. 1 an: abwechselnd rechts und links.": "Short standard exercises. Start with no. 1: alternate right and left.",
  "Oder": "Or",
  "24 kurze Handwechsel. Tempo bleibt gleich, nur die Folge ändert sich.": "24 short hand patterns. The tempo stays the same, only the sticking changes.",
  "Zurück zur Übersicht": "Back to overview",
  "Eine Minute im Puls bleiben": "Stay in the pulse for one minute",
  "Du hörst einen gleichmäßigen Klick — 80 Schläge pro Minute, das ist ein ruhiges Gehtempo. Bei jedem Klick ein Schlag auf dem Pad. Nicht schneller werden.": "You’ll hear a steady click — 80 beats per minute, a relaxed walking pace. Play one stroke on the pad with every click. Don’t speed up.",
  "Läuft": "Running",
  "Bleib am Pad. Jeder Klick = ein Schlag.": "Stay on the pad. Every click = one stroke.",
  "Sekunden": "seconds",
  "Überspringen": "Skip",
  // Trainer: gemeinsam
  "1 Takt": "1 bar",
  "2 Takte": "2 bars",
  "{n} Takte": "{n} bars",
  "Einzählen": "Count-in",
  // Click-Trainer
  "Click starten. Alle paar Sekunden wird das Tempo angehoben — Du bleibst am Pad.": "Start the click. Every few seconds the tempo goes up — you stay on the pad.",
  "Alle paar Sekunden wird das Tempo angehoben — Du bleibst am Pad.": "Every few seconds the tempo goes up — you stay on the pad.",
  "Gleichmäßiges Tempo halten. BPM am Kreis drehen oder ±5.": "Hold a steady tempo. Turn the dial or tap ±5 to set the BPM.",
  "Gleichmäßiges Tempo. Kreis drehen oder ±5.": "Steady tempo. Turn the dial or tap ±5.",
  "Tempo halten": "Hold tempo",
  "Tempo steigern": "Speed up",
  "Einstellung": "Settings",
  "Alle": "Every",
  "um": "faster by",
  "BPM schneller": "BPM",
  "bis": "up to",
  "Aktuell: Start {start}, alle {every}s +{step}, Ziel {cap}.": "Current: start {start}, every {every}s +{step}, target {cap}.",
  "Fester Puls bei {bpm} BPM. Drehen ändert das Tempo live.": "Steady pulse at {bpm} BPM. Turning changes the tempo live.",
  "Click-Mixer": "Click mixer",
  "Ziel": "Target",
  "Sek. bis +{step}": "sec to +{step}",
  "App im Hintergrund — der Click kann pausieren. Zurückkommen und ggf. neu starten.": "App in the background — the click may pause. Come back and restart if needed.",
  "Metronom": "Metronome",
  "Normal": "Normal",
  "Jede Zeile ist eine eigene Click-Ebene, der Lautsprecher regelt alle zusammen.": "Each row is its own click layer; the speaker controls them all.",
  "Änderungen gelten sofort, der Click läuft weiter.": "Changes apply instantly; the click keeps running.",
  "Viertel": "Quarter notes",
  "Grundpuls 1 2 3 4": "basic pulse 1 2 3 4",
  "Offbeat": "Offbeat",
  "das „und“ dazwischen": "the “and” in between",
  "16tel e/a": "16th notes e/a",
  "zwischen den Achteln": "between the 8ths",
  "Triolen": "Triplets",
  "2 und 3, 1 bleibt Viertel": "2 and 3; 1 stays a quarter",
  "BEAT": "BEAT",
  "betonte 1, anderer Klang": "accented 1, different sound",
  "Master": "Master",
  "Lautstärke aller Ebenen": "volume of all layers",
  // Rhythmuspyramide
  "Stufen wählen · immer 4/4.": "Choose levels · always 4/4.",
  "4tel": "Quarter notes",
  "8tel": "Eighth notes",
  "8tel-Triole": "Eighth-note triplets",
  "16tel": "16th notes",
  "Quintole": "Quintuplets",
  "16tel-Sextole": "16th-note sextuplets",
  "Septole": "Septuplets",
  "32tel": "32nd notes",
  "Richtung: Wie läuft die Pyramide?": "Direction: which way does the pyramid run?",
  "Aufwärts": "Up",
  "Abwärts": "Down",
  "Auf & ab": "Up & down",
  "Länge: Wie viele Takte pro Stufe?": "Length: how many bars per level?",
  "Takt übrig": "bar left",
  "Takte übrig": "bars left",
  "Pyramide fertig.": "Pyramid done.",
  "Jetzt": "Now",
  "Letzte Stufe": "Last level",
  "Wechsel in": "Change in",
  "Schlag": "beat",
  "Schlägen": "beats",
  "danach fertig": "then done",
  "Stufe {i}/{n}": "Level {i}/{n}",
  // Hand Control
  "Letzte Übung": "Last exercise",
  "Nr. {n}": "No. {n}",
  "Nummer {n}": "Exercise {n}",
  "DAVOR": "PREVIOUS",
  "Danach": "After that",
  "Wiederholungen": "Repeats",
  "Wiederholung": "Repeat",
  "Wdh.": "Reps",
  "Wiederholung {n} von {m}": "Repeat {n} of {m}",
  "Aus": "Off",
  "Bis Nr. 24 gehalten (ab Nr. {n}).": "Held through No. 24 (from No. {n}).",
  // Rudiments
  "Rudiment wählen": "Choose rudiment",
  "Frei": "Free",
  "8 Loops": "8 loops",
  "16 Loops": "16 loops",
  "2 Min": "2 min",
  "rud|Ziel": "Goal",
  "Klang": "Sound",
  "Geschafft!": "You did it!",
  "Antippen zum Schließen": "Tap to close",
  "Nur Click": "Click only",
  "rechts Floortom, links 14er Snare": "right hand floor tom, left hand 14-inch snare",
  // Noten (Archiv)
  "Tipp auf ein Blatt": "Tap a sheet",
  "Archiv auf diesem Gerät nicht verfügbar (privater Modus?).": "Storage isn’t available on this device (private mode?).",
  "Gespeichert auf diesem Gerät. Kopie extra in Dateien oder Cloud legen.": "Saved on this device. Keep a separate copy in Files or the cloud.",
  "Konnte das Blatt nicht speichern.": "Couldn’t save the sheet.",
  "Blatt vom Gerät löschen?": "Delete this sheet from the device?",
  "Blatt gelöscht.": "Sheet deleted.",
  "Name": "Name",
  "Name geändert.": "Name changed.",
  "Nur lokal": "Local only",
  "Liegt nur in diesem Browser. Gerätewechsel, Cache leeren oder App neu installieren kann alles löschen. Backup: Original-PDF/Foto extra in Dateien, Mail oder Cloud behalten.": "Stored only in this browser. Switching devices, clearing the cache or reinstalling the app can delete everything. Backup: keep the original PDF/photo in Files, email or the cloud.",
  "Hinzufügen": "Add",
  "Noch keine Blätter. Mit „Hinzufügen“ Foto oder PDF ablegen.": "No sheets yet. Tap “Add” to store a photo or PDF.",
  "Foto": "Photo",
  "Löschen": "Delete",
  "Archiv nicht verfügbar": "Storage not available",
  "abgebrochen": "cancelled",
  "Keine Datei.": "No file.",
  "Maximal 12 MB pro Blatt.": "Max. 12 MB per sheet.",
  "Nur Foto oder PDF.": "Photo or PDF only.",
  // Noten: bisher fehlende Übersetzungen (Archiv-Ansicht)
  "Deine Noten bleiben auf diesem Gerät": "Your sheet music stays on this device",
  "Fotos und PDFs werden nur hier im Browser gespeichert. Auf einem anderen Gerät siehst du sie nicht, und wenn du die Browserdaten löschst, sind sie weg. Bewahre deine Originale also zusätzlich woanders auf.": "Photos and PDFs are only saved here in your browser. You won’t see them on another device, and if you clear your browser data, they’re gone. So keep your originals somewhere else as well.",
  "Gespeichert. Extra-Kopie in Dateien oder Cloud legen.": "Saved. Keep an extra copy in Files or the cloud.",
  "Speichern fehlgeschlagen.": "Saving failed.",
  "Hier nicht verfügbar (privater Modus?).": "Not available here (private mode?).",
  "Gelöscht.": "Deleted.",
  "Noch nichts hier. Foto oder PDF hinzufügen.": "Nothing here yet. Add a photo or PDF.",
  // Noten: Vorschau, Auswahl, Vollbild
  "Notenblatt hinzufügen": "Add sheet",
  "Einzelseite": "Single page",
  "Auswählen": "Select",
  "Ausgewählt": "Selected",
  "Vorheriges Blatt": "Previous sheet",
  "Nächstes Blatt": "Next sheet",
  // Noten: Zoom
  "Vergrößern": "Zoom in",
  "Verkleinern": "Zoom out",
  "Ganze Seite zeigen": "Show whole page",
  "Ganz": "Fit",
  "Vorherige Seite": "Previous page",
  "Nächste Seite": "Next page",
  "Seite {n}/{m}": "Page {n}/{m}",
  "PDF konnte nicht angezeigt werden.": "The PDF could not be displayed.",
  "Zoomen": "Zoom",
  "Zwei Finger oder Doppeltipp zoomen bis 5×, gezoomt mit einem Finger verschieben. − / + / „Ganz“ unten; „Ganz“ zeigt wieder die ganze Seite.": "Pinch or double-tap to zoom up to 5×; when zoomed, drag with one finger. Use − / + / “Fit” at the bottom; “Fit” shows the whole page again.",
  // Noten: WA-22 Name + Tags, Suche, Filter, Sortierung
  "Name & Tags": "Name & tags",
  "Name & Tags bearbeiten: {name}": "Edit name & tags: {name}",
  "Tags": "Tags",
  "Tag hinzufügen": "Add tag",
  "Tag entfernen: {tag}": "Remove tag: {tag}",
  "Höchstens {n} Tags.": "At most {n} tags.",
  "Vorschläge": "Suggestions",
  "Optional, z. B. Paradiddle, Fills, Groove.": "Optional, e.g. paradiddle, fills, groove.",
  "Abbrechen": "Cancel",
  "Name und Tags gespeichert.": "Name and tags saved.",
  "Name/Tag suchen": "Search name/tag",
  "Suchen": "Search",
  "Sortieren": "Sort",
  "Neueste zuerst": "Newest first",
  "Älteste zuerst": "Oldest first",
  "Name A–Z": "Name A–Z",
  "Nach Tag filtern": "Filter by tag",
  "arch|Alle": "All",
  "{n} von {m}": "{n} of {m}",
  "Nichts gefunden.": "Nothing found.",
  "Filter zurücksetzen": "Reset filters",
  // Kurzhilfe Noten
  "Nur hier": "Only here",
  "Fotos und PDFs bleiben in diesem Browser, nichts wird hochgeladen. Auf einem anderen Gerät sind sie nicht da; Browserdaten löschen entfernt sie.": "Photos and PDFs stay in this browser; nothing is uploaded. They aren’t on your other devices, and clearing your browser data removes them.",
  "Foto oder PDF, maximal 12 MB.": "Photo or PDF, max. 12 MB.",
  "Pro Blatt Name und Tags vergeben. Oben suchen, nach Tag filtern, sortieren.": "Give each sheet a name and tags. Search at the top, filter by tag, sort.",
  "Ansehen": "View",
  "Blatt antippen öffnet die Vorschau (Einzelseite). ‚Auswählen‘ markiert es türkis und zeigt es im Vollbild.": "Tap a sheet to open the preview (single page). ‘Select’ marks it in teal and shows it full screen.",
  "Blättern": "Flip",
  "Im Vollbild mit ‹ › (oder Wischen) zum vorigen bzw. nächsten Blatt der Liste.": "In full screen, use ‹ › (or swipe) to go to the previous or next sheet in the list.",
  "Im Vollbild mit ‹ › (oder Wischen, wenn nicht gezoomt) zum vorigen bzw. nächsten Blatt der Liste.": "In full screen, use ‹ › (or swipe when not zoomed) to go to the previous or next sheet in the list.",
  // Drucken
  "Druckvorschau": "Print preview",
  "Vorschau · erste Seite": "Preview · first page",
  "Übungen anhaken — die Seite baut sich hier auf.": "Tick exercises — the page builds up here.",
  "Rudiments drucken": "Print rudiments",
  "Aktuelles Blatt: {name}": "Current sheet: {name}",
  "Übung": "Exercise",
  "Auswahl: 1 Übung": "Selected: 1 exercise",
  "Auswahl: {n} Übungen": "Selected: {n} exercises",
  "Vorschau unten.": "Preview below.",
  "{n} / Seite": "{n} / page",
  "print|Alle": "All",
  "Nur aktuelles Blatt": "Current sheet only",
  "jetzt": "now",
  "Speichern": "Save",
  "Teilen": "Share",
  "Vom Home-Bildschirm gibt es keinen Systemdruck. Speichern legt ein PNG ab.": "There’s no system printing from the home screen app. Save stores a PNG.",
  "Drucken öffnet den Systemdialog. Die App sagt danach Bescheid.": "Print opens the system dialog. The app lets you know afterwards.",
  "PNG gespeichert — Dateien / Downloads prüfen.": "PNG saved — check Files / Downloads.",
  "Speichern abgebrochen.": "Saving cancelled.",
  "Blatt wird erzeugt…": "Creating sheet…",
  "Teilen wird vorbereitet…": "Preparing to share…",
  "PNG wird erzeugt…": "Creating PNG…",
  "Keine Notation zum Export.": "No notation to export.",
  "Home-Bildschirm: Systemdruck fehlt. Blatt als PNG gespeichert.": "Home screen app: no system printing. Sheet saved as PNG.",
  "Druckdialog geöffnet. Fertig? Oben auf Zurück.": "Print dialog opened. Done? Tap Back at the top.",
  "Druck blockiert oder fehlgeschlagen — PNG gespeichert.": "Printing blocked or failed — PNG saved.",
  "Geteilt.": "Shared.",
  "Teilen nicht verfügbar — PNG gespeichert.": "Sharing not available — PNG saved.",
  "Teilen abgebrochen.": "Sharing cancelled.",
  "Konnte das Blatt nicht erzeugen. Bitte erneut versuchen.": "Couldn’t create the sheet. Please try again.",
  // Startseite: „Heute“-Karte (Mini-Pläne)
  "Heute": "Today",
  "Tagesquest": "Daily quest",
  "Tagesquest für heute überspringen": "Skip today’s daily quest",
  "Min": "min",
  "Plan": "Plan",
  "Plan wählen": "Choose a plan",
  "today|Grundlagen": "Basics",
  "today|Rudiments": "Rudiments",
  "today|Kurz": "Short",
  "Puls halten": "Hold the pulse",
  "Click-Trainer · 80 BPM": "Click Trainer · 80 BPM",
  "Click-Trainer · 70 BPM": "Click Trainer · 70 BPM",
  "Pyramide": "Pyramid",
  "4tel bis 32tel · 60 BPM": "Quarters to 32nds · 60 BPM",
  "ab Übung 1 · 70 BPM": "from exercise 1 · 70 BPM",
  "im Click bleiben · 80 BPM": "stay with the click · 80 BPM",
  "Eigene Noten": "Your sheet music",
  "ein Blatt durchspielen": "play one sheet through",
  // Startseite: „Nicht heute“ auf der Karte „Erste Übung starten“
  "Nicht heute": "Not today",
  "Erste Übung für heute ausblenden": "Hide the first lesson for today",
  // Rechtliches
  "Weitere Angaben": "More information",
  "Zum Impressum": "Go to Legal Notice",
  "Zur Datenschutzerklärung": "Go to Privacy Policy",
  // index.html
  "Rudiments und Grooves üben. Zeit für guten Sound.": "Practice rudiments and grooves. Time for great sound.",
};
