// Englisch: deutscher Originaltext → Übersetzung
export const EN = {
  // Home
  "Zeit für guten Sound": "Time for good sound",
  "Nochmal": "Again",
  "Loslegen": "Get started",
  "Erste Übung starten": "Start your first lesson",
  "Eine Minute mitklicken. Kein Fachwort nötig.": "One minute with the click. No jargon needed.",
  "Üben": "Practice",
  "40 PAS-Rudiments. Notation, Click, Tempo.": "40 PAS rudiments. Notation, click, tempo.",
  "Öffnen": "Open",
  "Starttempo wählen. Tempo halten oder automatisch steigern.": "Pick a start tempo. Hold it or speed up automatically.",
  "4tel bis 32tel: Puls festigen, sauber zwischen Unterteilungen wechseln, Tempo trotz Dichte halten.": "Quarters to 32nds: lock in the pulse, switch cleanly between subdivisions, hold the tempo as it gets denser.",
  "Technik": "Technique",
  "nach G. L. Stone: Schwache Hand verbessern, saubere Wechsel üben, Tempo ohne Verspannungen halten.": "After G. L. Stone: strengthen your weak hand, practice clean switches, keep the tempo without tension.",
  "Eigene Blätter": "Your sheets",
  "Fotos und PDFs lokal ablegen und währenddessen aufschlagen.": "Keep photos and PDFs on your device and open them while you play.",
  // Titel
  "Erste Übung": "First Lesson",
  "Click-Trainer": "Click Trainer",
  "Rhythmuspyramide": "Rhythm Pyramid",
  "Noten": "Sheet Music",
  "Impressum": "Legal Notice",
  "Datenschutz": "Privacy",
  // Kopfleiste
  "Zurück": "Back",
  "Drucken": "Print",
  "Blatt": "Sheet",
  "Übepad": "Pad",
  "Übepad aus": "Pad off",
  "Pad aus": "Pad off",
  "Notation groß, weniger Bedienelemente.": "Large notation, fewer controls.",
  // Logo-Metronom
  "Logo: Metronom öffnen": "Logo: open metronome",
  "Metronom schließen": "Close metronome",
  "5 BPM langsamer": "5 BPM slower",
  "5 BPM schneller": "5 BPM faster",
  // Metronom-Kreis
  "TIPP LINKS": "TURN LEFT",
  "= LANGSAMER": "= SLOWER",
  "TIPP RECHTS": "TURN RIGHT",
  "= SCHNELLER": "= FASTER",
  "Tipp = Start/Stop. Halten und drehen ändert das Tempo. Außen feiner.": "Tap = start/stop. Hold and turn to change the tempo. Finer further out.",
  "Metronom starten. Halten und drehen ändert das Tempo.": "Start metronome. Hold and turn to change the tempo.",
  "Metronom stoppen. Halten und drehen ändert das Tempo.": "Stop metronome. Hold and turn to change the tempo.",
  "Halten und drehen · außen feiner": "Hold and turn · finer outside",
  // Kurzhilfe
  "Kurzhilfe": "Quick help",
  "Kurz anschauen": "Quick look",
  "Kurz": "Quick help",
  "Einmalig beim ersten Öffnen — danach jederzeit über ?": "Shown once on first open — after that, anytime via ?",
  "Verstanden": "Got it",
  "Schließen": "Close",
  "40 PAS-Übungen. Notation lesen, Click hören, Tempo halten.": "40 PAS exercises. Read the notation, hear the click, hold the tempo.",
  "Metronom: Tempo steigern oder halten. Seite ‚Erweitert‘ = Click-Mixer.": "Metronome: speed up or hold the tempo. ‘Advanced’ side = click mixer.",
  "Subdivisionen auf und ab, 4tel bis 32tel.": "Subdivisions up and down, quarters to 32nds.",
  "24 Single-Beat-Nummern. Challenge spielt 1–24 durch.": "24 single-beat exercises. Challenge plays 1–24 in a row.",
  "Eigene Fotos/PDFs nur auf diesem Gerät. Beim Üben über Blatt.": "Your own photos/PDFs, only on this device. Open them while practicing via Sheet.",
  "Kreis": "Dial",
  "Tippen = Start/Stop. Halten + drehen = Tempo.": "Tap = start/stop. Hold + turn = tempo.",
  "Metronom unten": "Metronome (bottom)",
  "Tippen = Start/Stop. Halten + drehen: rechtsrum schneller.": "Tap = start/stop. Hold + turn: clockwise = faster.",
  "Radius": "Radius",
  "Innen grob, außen fein, auch über den Ring hinaus. −5/+5 daneben.": "Coarse near the center, fine further out, even beyond the ring. −5/+5 next to it.",
  "Nav unten": "Bottom nav",
  "‹ › tippen = vor/zurück. Wischen springt mehrere. Halten öffnet das Zahlenrad.": "Tap ‹ › = next/previous. Swipe to skip several. Hold to open the number wheel.",
  "Titel": "Title",
  "‚Rudiment wählen‘ + ▾ öffnet die komplette Liste.": "‘Choose rudiment’ + ▾ opens the full list.",
  "Hören": "Sound",
  "Snare, L/R oder Nur Click — Umschalter über dem Kreis.": "Snare, L/R or click only — switch above the dial.",
  "Erweitert": "Advanced",
  "Seitenstreifen ‚Erweitert‘ dreht die Kachel. Mixer für Viertel, Offbeat, 16tel, Triolen, Beat und Master. Der Click läuft dabei weiter.": "The ‘Advanced’ side strip flips the card. Mixer for quarters, offbeats, 16ths, triplets, beat and master. The click keeps running.",
  "Modi": "Modes",
  "Tempo halten oder steigern (alle X Sekunden +Y BPM).": "Hold or increase the tempo (every X seconds +Y BPM).",
  "Tippen = Start/Stop. Halten + drehen = Tempo, innen grob, außen fein, auch über den Ring hinaus. −5/+5 daneben.": "Tap = start/stop. Hold + turn = tempo, coarse near the center, fine further out, even beyond the ring. −5/+5 next to it.",
  "Stufen": "Levels",
  "4tel → 8tel → 8tel-Triole → 16tel → Quintole → 16tel-Sextole → Septole → 32tel. Tippen schaltet einzeln an/aus, eine bleibt immer an.": "Quarters → 8ths → 8th triplets → 16ths → quintuplets → 16th sextuplets → septuplets → 32nds. Tap to switch each on/off; one always stays on.",
  "Takte": "Bars",
  "1, 2 oder 4 Takte pro Stufe, immer im 4/4.": "1, 2 or 4 bars per level, always in 4/4.",
  "Tippen = Start/Stop. Drehen = Tempo, innen grob, außen fein. −5/+5 daneben.": "Tap = start/stop. Turn = tempo, coarse near the center, fine further out. −5/+5 next to it.",
  "‹ › oder wischen. Halten öffnet das Rad, Vorschau = erste 8 Achtel.": "‹ › or swipe. Hold to open the wheel; preview = first 8 eighths.",
  "Liste": "List",
  "Nach oben scrollen zeigt frühere Nummern, nach unten die nächsten. Die aktuelle bleibt oben angeheftet.": "Scroll up for earlier exercises, down for the next ones. The current one stays pinned at the top.",
  "Challenge": "Challenge",
  "1–24 durchspielen. Wiederholungen = komplette Übung (beide Takte). Einzählen nur am Start, nicht zwischen den Nummern.": "Play through 1–24. Repeats = the whole exercise (both bars). Count-in only at the start, not between exercises.",
  "Lokal": "Local",
  "Dateien bleiben im Browser dieses Geräts. Kein Upload in die Cloud.": "Files stay in this device’s browser. Nothing is uploaded to the cloud.",
  "Format": "Format",
  "Foto oder PDF, bis 12 MB.": "Photo or PDF, up to 12 MB.",
  "In Rudiments u. a. über Blatt öffnen — Playback läuft weiter.": "Open via Sheet in Rudiments and other trainers — playback keeps running.",
  // Erste Übung
  "Fertig": "Done",
  "Eine Minute gehalten.": "You held it for a minute.",
  "Als Nächstes: eine einfache Figur mit rechts/links — oder die Hände einzeln sauber wechseln.": "Next up: a simple right/left pattern — or clean switches between your hands.",
  "Als Nächstes": "Next up",
  "Kleine Standard-Übungen. Fang mit Nr. 1 an: abwechselnd rechts und links.": "Short standard exercises. Start with no. 1: alternate right and left.",
  "Oder": "Or",
  "24 kurze Handwechsel. Tempo bleibt gleich, nur die Folge ändert sich.": "24 short hand patterns. The tempo stays the same, only the sticking changes.",
  "Zurück zur Übersicht": "Back to overview",
  "Eine Minute im Puls bleiben": "Stay in the pulse for one minute",
  "Du hörst einen gleichmäßigen Klick — 80 Schläge pro Minute, das ist ein ruhiges Gehtempo. Bei jedem Klick ein Schlag auf dem Pad. Nicht schneller werden.": "You’ll hear a steady click — 80 beats per minute, a relaxed walking pace. Play one stroke on the pad with every click. Don’t speed up.",
  "Läuft": "Running",
  "Bleib am Pad. Jeder Klick = ein Schlag.": "Stay on the pad. Every click = one stroke.",
  "Sekunden": "seconds",
  "Überspringen": "Skip",
  // Trainer: gemeinsam
  "1 Takt": "1 bar",
  "2 Takte": "2 bars",
  "{n} T.": "{n} bars",
  "Einzählen": "Count-in",
  // Click-Trainer
  "Click starten. Alle paar Sekunden wird das Tempo angehoben — Du bleibst am Pad.": "Start the click. Every few seconds the tempo goes up — you stay on the pad.",
  "Gleichmäßiges Tempo halten. BPM am Kreis drehen oder ±5.": "Hold a steady tempo. Turn the dial or tap ±5 to set the BPM.",
  "Tempo halten": "Hold tempo",
  "Tempo steigern": "Speed up",
  "Einstellung": "Settings",
  "Alle": "Every",
  "um": "faster by",
  "BPM schneller": "BPM",
  "bis": "up to",
  "Beispiel: Start {start}, alle {every}s +{step}, Ziel {cap}.": "Example: start {start}, every {every}s +{step}, target {cap}.",
  "Fester Puls bei {bpm} BPM. Drehen ändert das Tempo live.": "Steady pulse at {bpm} BPM. Turning changes the tempo live.",
  "Click-Mixer": "Click mixer",
  "Ziel": "Target",
  "Sek. bis +{step}": "sec to +{step}",
  "App im Hintergrund — der Click kann pausieren. Zurückkommen und ggf. neu starten.": "App in the background — the click may pause. Come back and restart if needed.",
  "Metronom": "Metronome",
  "Normal": "Normal",
  "Jede Zeile ist eine eigene Click-Ebene, der Lautsprecher regelt alle zusammen.": "Each row is its own click layer; the speaker controls them all.",
  "Änderungen gelten sofort, der Click läuft weiter.": "Changes apply instantly; the click keeps running.",
  "Viertel": "Quarters",
  "Grundpuls 1 2 3 4": "basic pulse 1 2 3 4",
  "Offbeat": "Offbeat",
  "das „und“ dazwischen": "the “and” in between",
  "16tel e/a": "16ths e/a",
  "zwischen den Achteln": "between the 8ths",
  "Triolen": "Triplets",
  "2 und 3, 1 bleibt Viertel": "2 and 3; 1 stays a quarter",
  "BEAT": "BEAT",
  "betonte 1, anderer Klang": "accented 1, different sound",
  "Master": "Master",
  "Lautstärke aller Ebenen": "volume of all layers",
  // Rhythmuspyramide
  "Stufen wählen · immer 4/4.": "Choose levels · always 4/4.",
  "4tel": "Quarters",
  "8tel": "8ths",
  "8tel-Triole": "8th triplets",
  "16tel": "16ths",
  "Quintole": "Quintuplets",
  "16tel-Sextole": "16th sextuplets",
  "Septole": "Septuplets",
  "32tel": "32nds",
  "auf": "up",
  "ab": "down",
  "auf+ab": "up+down",
  "Takt übrig": "bar left",
  "Takte übrig": "bars left",
  "Pyramide fertig.": "Pyramid done.",
  // Stick Control
  "Nr. {n}": "No. {n}",
  "Nummer {n}": "Exercise {n}",
  "DAVOR": "PREVIOUS",
  "Wiederholungen": "Repeats",
  "Aus": "Off",
  "Bis Nr. 24 gehalten (ab Nr. {n}).": "Held through No. 24 (from No. {n}).",
  // Rudiments
  "Rudiment wählen": "Choose rudiment",
  "Frei": "Free",
  "8 Loops": "8 loops",
  "16 Loops": "16 loops",
  "2 Min": "2 min",
  "Ziel gehalten — weiter so.": "Goal reached — keep it up.",
  "Aktueller Schlag oben markiert · R blau · L rot": "Current beat marked on top · R blue · L red",
  "Nur Click": "Click only",
  // Noten (Archiv)
  "Tipp auf ein Blatt": "Tap a sheet",
  "Archiv auf diesem Gerät nicht verfügbar (privater Modus?).": "Storage isn’t available on this device (private mode?).",
  "Gespeichert auf diesem Gerät. Kopie extra in Dateien oder Cloud legen.": "Saved on this device. Keep a separate copy in Files or the cloud.",
  "Konnte das Blatt nicht speichern.": "Couldn’t save the sheet.",
  "Blatt vom Gerät löschen?": "Delete this sheet from the device?",
  "Blatt gelöscht.": "Sheet deleted.",
  "Name": "Name",
  "Name geändert.": "Name changed.",
  "Nur lokal": "Local only",
  "Liegt nur in diesem Browser. Gerätewechsel, Cache leeren oder App neu installieren kann alles löschen. Backup: Original-PDF/Foto extra in Dateien, Mail oder Cloud behalten.": "Stored only in this browser. Switching devices, clearing the cache or reinstalling the app can delete everything. Backup: keep the original PDF/photo in Files, email or the cloud.",
  "Hinzufügen": "Add",
  "Links": "Left",
  "Rechts": "Right",
  "links": "left",
  "rechts": "right",
  "Noch keine Blätter. Mit „Hinzufügen“ Foto oder PDF ablegen.": "No sheets yet. Tap “Add” to store a photo or PDF.",
  "Foto": "Photo",
  "Löschen": "Delete",
  "Archiv nicht verfügbar": "Storage not available",
  "abgebrochen": "cancelled",
  "Keine Datei.": "No file.",
  "Maximal 12 MB pro Blatt.": "Max. 12 MB per sheet.",
  "Nur Foto oder PDF.": "Photo or PDF only.",
  // Drucken
  "Druckvorschau": "Print preview",
  "Vorschau · erste Seite": "Preview · first page",
  "Übungen anhaken — die Seite baut sich hier auf.": "Tick exercises — the page builds up here.",
  "Rudiments drucken": "Print rudiments",
  "Aktuelles Blatt: {name}": "Current sheet: {name}",
  "Übung": "Exercise",
  "Auswahl: 1 Übung": "Selected: 1 exercise",
  "Auswahl: {n} Übungen": "Selected: {n} exercises",
  "Vorschau unten.": "Preview below.",
  "{n} / Seite": "{n} / page",
  "print|Alle": "All",
  "Nur aktuelles Blatt": "Current sheet only",
  "jetzt": "now",
  "Speichern": "Save",
  "Teilen": "Share",
  "Vom Home-Bildschirm gibt es keinen Systemdruck. Speichern legt ein PNG ab.": "There’s no system printing from the home screen app. Save stores a PNG.",
  "Drucken öffnet den Systemdialog. Die App sagt danach Bescheid.": "Print opens the system dialog. The app lets you know afterwards.",
  "PNG gespeichert — Dateien / Downloads prüfen.": "PNG saved — check Files / Downloads.",
  "Speichern abgebrochen.": "Saving cancelled.",
  "Blatt wird erzeugt…": "Creating sheet…",
  "Teilen wird vorbereitet…": "Preparing to share…",
  "PNG wird erzeugt…": "Creating PNG…",
  "Keine Notation zum Export.": "No notation to export.",
  "Home-Bildschirm: Systemdruck fehlt. Blatt als PNG gespeichert.": "Home screen app: no system printing. Sheet saved as PNG.",
  "Druckdialog geöffnet. Fertig? Oben auf Zurück.": "Print dialog opened. Done? Tap Back at the top.",
  "Druck blockiert oder fehlgeschlagen — PNG gespeichert.": "Printing blocked or failed — PNG saved.",
  "Geteilt.": "Shared.",
  "Teilen nicht verfügbar — PNG gespeichert.": "Sharing not available — PNG saved.",
  "Teilen abgebrochen.": "Sharing cancelled.",
  "Konnte das Blatt nicht erzeugen. Bitte erneut versuchen.": "Couldn’t create the sheet. Please try again.",
};
